# For more information: https://laravel.com/docs/sail
version: "3"
name: "app"
services:
    laravel:
        container_name: laravel
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
            args:
                - APP_DEBUG=true
        # ports:
        #     - "9000:9000"
        volumes:
            - ./:/var/www
        working_dir: "/var/www"
        networks:
            - sail
        depends_on:
            - mysql
            - minio
            - mailhog
            - redis
    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./public:/var/www/public
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - sail
        depends_on:
            - laravel
    mysql:
        container_name: mysql
        image: "mysql"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            # MYSQL_USER: "${DB_USERNAME}"
            # MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./.docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        ports:
            - 2807:80
        networks:
            - sail
        depends_on:
            - mysql
        environment:
            PMA_HOST: "${DB_HOST}"
            PMA_PORT: "${DB_PORT}"
            PMA_PASSWORD: "${DB_PASSWORD}"
            PMA_ARBITRARY: 1
    minio:
        container_name: minio
        image: "minio/minio:latest"
        ports:
            - "${FORWARD_MINIO_PORT:-9001}:9000"
            - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
        environment:
            MINIO_ROOT_USER: "sail"
            MINIO_ROOT_PASSWORD: "password"
        volumes:
            - "sail-minio:/data/minio"
        networks:
            - sail
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s
    mailhog:
        container_name: mailhog
        image: "mailhog/mailhog:latest"
        ports:
            - "${FORWARD_MAILHOG_PORT:-1025}:1025"
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        tty: true
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:${REDIS_PORT}"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-minio:
        driver: local
